### ISSUE TITLE
Error when authenticating user

### ISSUE THREAD

**Issue by alexrs** [zmb3/spotify#20] opened 2017-01-13 22:33 UTC
Running the auth example of the library returns the following error:

```BASH
2017/01/13 23:32:10 Post https://accounts.spotify.com/api/token: stream error: stream ID 1; REFUSED_STREAM
```

UPDATE:
If it is executed with `GODEBUG=http2client=0` it seems to work. This is the output I get when I set `GODEBUG=http2debug=2`:

```BASH
2017/01/13 23:33:57 http2: Transport failed to get client conn for accounts.spotify.com:443: http2: no cached connection was available
2017/01/13 23:33:57 http2: Transport creating client conn 0xc4200901a0 to 194.132.196.226:443
2017/01/13 23:33:57 http2: Framer 0xc4202f5800: wrote SETTINGS len=18, settings: ENABLE_PUSH=0, INITIAL_WINDOW_SIZE=4194304, MAX_HEADER_LIST_SIZE=10485760
2017/01/13 23:33:57 http2: Framer 0xc4202f5800: wrote WINDOW_UPDATE len=4 (conn) incr=1073741824
2017/01/13 23:33:57 http2: Transport encoding header ":authority" = "accounts.spotify.com"
2017/01/13 23:33:57 http2: Transport encoding header ":method" = "POST"
2017/01/13 23:33:57 http2: Transport encoding header ":path" = "/api/token"
2017/01/13 23:33:57 http2: Transport encoding header ":scheme" = "https"
2017/01/13 23:33:57 http2: Transport encoding header "content-type" = "application/x-www-form-urlencoded"
2017/01/13 23:33:57 http2: Transport encoding header "authorization" = "Basic NDEzZGY5N2FlOTZmNDliODgxN2Q1MzIyNzg4YjI0YzI6NDM5Mzk3Zjg1OGM4NGE3ZWJmOTUzMzFmZjA2NjA3ZDY="
2017/01/13 23:33:57 http2: Transport encoding header "content-length" = "379"
2017/01/13 23:33:57 http2: Transport encoding header "accept-encoding" = "gzip"
2017/01/13 23:33:57 http2: Transport encoding header "user-agent" = "Go-http-client/2.0"
2017/01/13 23:33:57 http2: Framer 0xc4202f5800: wrote HEADERS flags=END_HEADERS stream=1 len=158
2017/01/13 23:33:57 http2: Framer 0xc4202f5800: wrote DATA stream=1 len=379 data="client_id=MY_ID&code=AQAGHoYEEByHqEm9ecc22P9zqQTegw5D89DIswksVSmMcNFTcje5neDqJlNRpmxRyBihut-LCd7pLZr9vw5ltoXM2hRtTcE8yPnOFHEpzfhHxrsNOV-NnW77HMQku1X291AXOI8434rpv8t-B-5RxB62jJ9BTtumniPvSqondV1nG-UfaEoYsYNsN3VS3P17K96TknTlE9NSgmzX" (123 bytes omitted)
2017/01/13 23:33:57 http2: Framer 0xc4202f5800: wrote DATA flags=END_STREAM stream=1 len=0 data=""
2017/01/13 23:33:57 http2: Framer 0xc4202f5800: read SETTINGS len=18, settings: MAX_CONCURRENT_STREAMS=128, INITIAL_WINDOW_SIZE=0, MAX_FRAME_SIZE=16777215
2017/01/13 23:33:57 http2: Transport received SETTINGS len=18, settings: MAX_CONCURRENT_STREAMS=128, INITIAL_WINDOW_SIZE=0, MAX_FRAME_SIZE=16777215
2017/01/13 23:33:57 http2: Framer 0xc4202f5800: wrote SETTINGS flags=ACK len=0
2017/01/13 23:33:57 http2: Framer 0xc4202f5800: read WINDOW_UPDATE len=4 (conn) incr=2147418112
2017/01/13 23:33:57 http2: Transport received WINDOW_UPDATE len=4 (conn) incr=2147418112
2017/01/13 23:33:57 http2: Framer 0xc4202f5800: read SETTINGS flags=ACK len=0
2017/01/13 23:33:57 http2: Transport received SETTINGS flags=ACK len=0
2017/01/13 23:33:57 http2: Framer 0xc4202f5800: read RST_STREAM stream=1 len=4 ErrCode=REFUSED_STREAM
2017/01/13 23:33:57 http2: Transport received RST_STREAM stream=1 len=4 ErrCode=REFUSED_STREAM
2017/01/13 23:33:57 RoundTrip failure: stream error: stream ID 1; REFUSED_STREAM
2017/01/13 23:33:57 Post https://accounts.spotify.com/api/token: stream error: stream ID 1; REFUSED_STREAM
exit status 1
```

**Comment by zmb3** [comment] 2017-01-16 22:33
It seems Spotify doesn't currently support HTTP2 (see spotify/web-api#398).

For now I recommend setting `GODEBUG=http2client=0` to disable the HTTP2 client.
I'm debating whether or not it makes sense to do this in the library or to simply wait for Spotify to fix things.

**Comment by Alexrs95** [comment] 2017-01-16 22:41
I have been investigating, and I have found that the use of HTTP/2 can be avoided [overriding Transport.TLSNextProto](https://golang.org/pkg/net/http/#pkg-overview), but the problem is in the oauth2 lib, when the token is obtained, (see [oauth2/internal](https://github.com/golang/oauth2/blob/master/internal/token.go#L152), and we can't access to that http.Client (at least I don't know how to do it) to override that field, so apparently, the only possible workaround is setting `GODEBUG=http2client=0`.

**Comment by zmb3** [comment] 2017-01-16 22:48
We could override the client that the oauth2 lib uses by specifying it in the context.

It would look something like:

`ctx = context.WithValue(ctx, oauth2.HTTPClient, c.http)`

However this library was written before `context.Context` was a thing and uses the [now deprecated] `oauth2.NoContext` placeholder everywhere.  It really needs a good "V2" refactoring so that all calls accept a context.  This isn't a priority for me at the moment but if someone wanted to step in and take some of that work on I'd welcome the help :-)

**Comment by hughrawlinson** [comment] 2017-01-17 13:57
@zmb3 for clarity, we at Spotify have no current plans to support HTTP2 in our authentication service. I would recommend changing the library to account for this. We'll be sure to announce any HTTP2 related changes, so keep an eye on @SpotifyPlatform or our blog on developer.spotify.com.

**Comment by cescoferraro** [comment] 2017-01-17 16:00
I see these stream error randomly while developing. A refresh always work, Its really annoying.

```
[00] [00] 2017/01/17 15:50:29 "OPTIONS http://localhost:8080/me/AQDikk934ygF0yPCM7J78sF0WSE8e-39HAHbkuK8NigavmGLs2J9ZPOF_Q1AVu83sSJUE91ae-YA-WwyqWz1OG4fzxSgPZQC7SElmJryHqDferQnqHHfun00hQlWe8Ik8Boume_XJa7DfT-j-4pluY9fgnk126s_t_OR4hfWw2OIgklD2zZZbBKOvZ3b69YuTTkVE7WN1hHdO7PwLH3JKFEquYkwR6xzY3V_Hh82zaML7dU6dyXP9KlD5EwsT4pFpAwKkH2GzrqtxxfsGyYUAQwhBrRux9RIw62jfu3EmZSmJt5_MmfmoU3Q3t7gP8Os6rn2cpw6wEyzEAeSN7yZU4jLRTCMwg HTTP/1.1" from [::1]:48618 - 200 0B in 11.17µs
[00] [00] 2017/01/17 15:50:29 Code is AQDikk934ygF0yPCM7J78sF0WSE8e-39HAHbkuK8NigavmGLs2J9ZPOF_Q1AVu83sSJUE91ae-YA-WwyqWz1OG4fzxSgPZQC7SElmJryHqDferQnqHHfun00hQlWe8Ik8Boume_XJa7DfT-j-4pluY9fgnk126s_t_OR4hfWw2OIgklD2zZZbBKOvZ3b69YuTTkVE7WN1hHdO7PwLH3JKFEquYkwR6xzY3V_Hh82zaML7dU6dyXP9KlD5EwsT4pFpAwKkH2GzrqtxxfsGyYUAQwhBrRux9RIw62jfu3EmZSmJt5_MmfmoU3Q3t7gP8Os6rn2cpw6wEyzEAeSN7yZU4jLRTCMwg
[00] [00] 2017/01/17 15:50:29 retrieving Token ....
[00] [00] 2017/01/17 15:50:29 checking if token exists ....
[00] [00] 2017/01/17 15:50:29 Exchange SPOTIFYAUTH ....
[00] [00] 2017/01/17 15:50:29 ERROR: Exchange SPOTIFYAUTH : Post https://accounts.spotify.com/api/token: stream error: stream ID 1; REFUSED_STREAM
[00] [00] 2017/01/17 15:50:29 ERROR: retrieving Token : Post https://accounts.spotify.com/api/token: stream error: stream ID 1; REFUSED_STREAM
[00] [00] 2017/01/17 15:50:29 Post https://accounts.spotify.com/api/token: stream error: stream ID 1; REFUSED_STREAM
[00] [00] 2017/01/17 15:50:29 "GET http://localhost:8080/me/AQDikk934ygF0yPCM7J78sF0WSE8e-39HAHbkuK8NigavmGLs2J9ZPOF_Q1AVu83sSJUE91ae-YA-WwyqWz1OG4fzxSgPZQC7SElmJryHqDferQnqHHfun00hQlWe8Ik8Boume_XJa7DfT-j-4pluY9fgnk126s_t_OR4hfWw2OIgklD2zZZbBKOvZ3b69YuTTkVE7WN1hHdO7PwLH3JKFEquYkwR6xzY3V_Hh82zaML7dU6dyXP9KlD5EwsT4pFpAwKkH2GzrqtxxfsGyYUAQwhBrRux9RIw62jfu3EmZSmJt5_MmfmoU3Q3t7gP8Os6rn2cpw6wEyzEAeSN7yZU4jLRTCMwg HTTP/1.1" from [::1]:48618 - 500 87B in 684.561148ms

```

Then a refresh works 

```
[00] [00] 2017/01/17 15:53:14 "OPTIONS http://localhost:8080/me/AQDikk934ygF0yPCM7J78sF0WSE8e-39HAHbkuK8NigavmGLs2J9ZPOF_Q1AVu83sSJUE91ae-YA-WwyqWz1OG4fzxSgPZQC7SElmJryHqDferQnqHHfun00hQlWe8Ik8Boume_XJa7DfT-j-4pluY9fgnk126s_t_OR4hfWw2OIgklD2zZZbBKOvZ3b69YuTTkVE7WN1hHdO7PwLH3JKFEquYkwR6xzY3V_Hh82zaML7dU6dyXP9KlD5EwsT4pFpAwKkH2GzrqtxxfsGyYUAQwhBrRux9RIw62jfu3EmZSmJt5_MmfmoU3Q3t7gP8Os6rn2cpw6wEyzEAeSN7yZU4jLRTCMwg HTTP/1.1" from [::1]:48618 - 200 0B in 9.382µs
[00] [00] 2017/01/17 15:53:14 Code is AQDikk934ygF0yPCM7J78sF0WSE8e-39HAHbkuK8NigavmGLs2J9ZPOF_Q1AVu83sSJUE91ae-YA-WwyqWz1OG4fzxSgPZQC7SElmJryHqDferQnqHHfun00hQlWe8Ik8Boume_XJa7DfT-j-4pluY9fgnk126s_t_OR4hfWw2OIgklD2zZZbBKOvZ3b69YuTTkVE7WN1hHdO7PwLH3JKFEquYkwR6xzY3V_Hh82zaML7dU6dyXP9KlD5EwsT4pFpAwKkH2GzrqtxxfsGyYUAQwhBrRux9RIw62jfu3EmZSmJt5_MmfmoU3Q3t7gP8Os6rn2cpw6wEyzEAeSN7yZU4jLRTCMwg
[00] [00] 2017/01/17 15:53:14 retrieving Token ....
[00] [00] 2017/01/17 15:53:14 checking if token exists ....
[00] [00] 2017/01/17 15:53:14 Exchange SPOTIFYAUTH ....
[00] [00] 2017/01/17 15:53:14 Token is &{BQDJsZC1KDO_j6W1NDt-UAP2N26keptTwyvtJXGlVaibV8scYUlOUAlZY_6lL_ovddFRSdP2CAhlAg6q8PIB2e2RxR8w6rDY1b48QsMvBVtxBZx_oUUB3micgtprWEPKp6_pZR4Aql6rfxWjiGQwqNFeDQEU61m41DLGIvQ2R0n94c1Yy04yUzZd-7Dd0R7-S4vdqIGwuz-SJAeZVAlfD3ThAHAtxgyVCtlpLDfxjhe8GscprGKbXhl5wAm1IJPbmNYhO3Rx Bearer AQDV_X7Nb5F83Y8KNa3AMqvFWncs4P1RKODIpyxELQbuxae8MD8_mUdHer5g1-Bxrf5rxZA9997tDcb_eh9aacxOazzpOsAMG7w_6E7J7olLNpRpnqeQCefx1pk6-1RUFHk 2017-01-17 16:53:14.635773385 +0000 UTC map[access_token:BQDJsZC1KDO_j6W1NDt-UAP2N26keptTwyvtJXGlVaibV8scYUlOUAlZY_6lL_ovddFRSdP2CAhlAg6q8PIB2e2RxR8w6rDY1b48QsMvBVtxBZx_oUUB3micgtprWEPKp6_pZR4Aql6rfxWjiGQwqNFeDQEU61m41DLGIvQ2R0n94c1Yy04yUzZd-7Dd0R7-S4vdqIGwuz-SJAeZVAlfD3ThAHAtxgyVCtlpLDfxjhe8GscprGKbXhl5wAm1IJPbmNYhO3Rx token_type:Bearer expires_in:%!s(float64=3600) refresh_token:AQDV_X7Nb5F83Y8KNa3AMqvFWncs4P1RKODIpyxELQbuxae8MD8_mUdHer5g1-Bxrf5rxZA9997tDcb_eh9aacxOazzpOsAMG7w_6E7J7olLNpRpnqeQCefx1pk6-1RUFHk scope:user-follow-modify user-follow-read playlist-modify-private playlist-modify-public user-read-email user-read-private]}
[00] [00] 2017/01/17 15:53:14 Gouroutine will Sleep 10 Minute ....
[00] [00] 2017/01/17 15:53:15 "GET http://localhost:8080/me/AQDikk934ygF0yPCM7J78sF0WSE8e-39HAHbkuK8NigavmGLs2J9ZPOF_Q1AVu83sSJUE91ae-YA-WwyqWz1OG4fzxSgPZQC7SElmJryHqDferQnqHHfun00hQlWe8Ik8Boume_XJa7DfT-j-4pluY9fgnk126s_t_OR4hfWw2OIgklD2zZZbBKOvZ3b69YuTTkVE7WN1hHdO7PwLH3JKFEquYkwR6xzY3V_Hh82zaML7dU6dyXP9KlD5EwsT4pFpAwKkH2GzrqtxxfsGyYUAQwhBrRux9RIw62jfu3EmZSmJt5_MmfmoU3Q3t7gP8Os6rn2cpw6wEyzEAeSN7yZU4jLRTCMwg HTTP/1.1" from [::1]:48618 - 200 528B in 982.134711ms
```


But recently I am trying to migrate an app from digital ocean to AWS, and my authenticator times out to exchange token with the Spotify API. It seems like an aws issue like if the outbound ports were closed, but is most def not the case. All traffic is opened


```
2017/01/17 15:44:18 checking if token exists ....
2017/01/17 15:44:18 Exchange SPOTIFYAUTH ....
2017/01/17 15:44:48 "GET http://spotify.api.cescoferraro.xyz/me/AQD6sHu5Suu9eoz2lPa15w2VZ0IXf5awR4YbXvAuBPO6Oykothwi1TgJF9rpw6MZqkgNOxkWb4FAl5jIp8HgV4r-iddwLnosKG7jnFQXSc2VZrl0rZ0tEwIyjFngKSbRui0N0E7PgP4BE6Ulf2HB5pPVr7IbEUPQBxtJf4tFbjl6SPGow1LIqEOANX--IvptwjHmFvF9EQCw7B2qBXcpXh1HVIAsP3dJsA3Mlnz2c32x-nhkIp-QjAEq-xAtZT-qVKAuG0dlOqMQ8uyaQLQyeE-gHPUXIZq7Mx8nD9Ba6DoJygVcBC6BJbUZYQmp45rTB1C7wm1k4LsKZ5NZfYmlVOc1DnuWuWqZqEqf8kZl6a0kF0AU HTTP/1.1" from 172.17.0.3:54250 - 500 67B in 1m41.382965921s
2017/01/17 15:44:48 ERROR: Exchange SPOTIFYAUTH : Post https://accounts.spotify.com/api/token: dial tcp: i/o timeout
2017/01/17 15:44:48 ERROR: retrieving Token : Post https://accounts.spotify.com/api/token: dial tcp: i/o timeout
2017/01/17 15:44:48 Post https://accounts.spotify.com/api/token: dial tcp: i/o timeout
```

**Comment by zmb3** [comment] 2018-02-12 04:06
Going to close this as it seems we understand and have addressed the root cause (http2).

**Closed by zmb3** 2018-02-12 04:06 UTC
