### ISSUE TITLE
PlayerCurrentlyPlaying() returns error EOF when nothing is playing

### ISSUE THREAD

**Issue by Nikos410** [zmb3/spotify#109] opened 2019-12-09 18:44 UTC
Hi there! 

I noticed that the function `client.PlayerCurrentlyPlaying()` returns an error with the message EOF when no song is currently playing.

The error occurs when [trying to decode an empty response body](https://github.com/zmb3/spotify/blob/869e03d/spotify.go#L184).
```go
if result != nil {
    if err := json.NewDecoder(resp.Body).Decode(result); err != nil {
        return err
    }
}
```
![Debugger Screenshot](https://user-images.githubusercontent.com/20876882/70462707-bd93ad80-1abb-11ea-9465-4c742755f6a2.png)

I would offer to submit a PR to fix this, but this is actually the first project I'm working on using go, so I'm not sure how to approach this issue.

Thanks!

**Comment by zmb3** [comment] 2019-12-10 17:27
Hey there, thanks for the issue.

This looks to be a duplicate of #72, which should have been fixed by #88, but it looks like we only made the 204 check in `*Client.get()` and not in `*Client.execute()`.

As I look at `get` and `execute` I spot other subtle differences as well (retry logic, error decoding, etc).

It looks like we need to make a similar `if resp.StatusCode == http.StatusNoContent` check in `execute` so that `get` and `execute` behave the same.  At that point, we might as well do away with the `get` helper and just use execute everywhere to avoid having to maintain such similar methods.

**Closed** 2019-12-13 13:54 UTC
